# Generated by Django 6.0.3 on 2026-05-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_numbered',
            field=models.BooleanField(default=False, verbose_name='Участвует в тесте по картинке'),
        ),
        migrations.AddField(
            model_name='question',
            name='number_correct',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Правильная цифра'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True),
        ),
    ]
